export const sampleEvents = [
  "Network disconnected in region",
  "System reboot completed",
  "Backup initiated",
  "User authenticated successfully",
  "Error log updated",
  "Payment processed successfully",
  "API returned 200 OK",
  "Data synchronized with server",
  "Unauthorized access detected",
  "High memory usage alert",
  "Server recovery in progress",
  "Reduced service speed",
  "Maintenance scheduled for midnight",
  "Malware removed from system",
  "New deployment to production",
  "New user registered",
  "Load balancing across servers",
  "Security patch applied",
  "Data migration completed",
  "Failed login attempt",
  "File uploaded successfully",
  "Error notification sent to admin",
  "User session timed out",
  "System configuration updated",
  "IP added to whitelist",
  "Database optimized",
  "Session expired",
  "New user role assigned",
  "Account locked due to multiple attempts",
  "New configuration applied",
  "Error handled by fallback",
  "CPU usage critical threshold reached",
  "Memory allocation increased",
  "Access revoked for inactive user",
  "Account settings updated",
  "Automatic restart triggered",
  "Daily backup completed",
  "Alert: database query exceeded time limit",
  "Permissions updated",
  "Rate limiting triggered on endpoint",
  "Data validation failed",
  "Reconnected after network instability",
];
