export const sampleIntersections = [
  "Network Outage",
  "System Update",
  "Database Backup",
  "User Login",
  "Error Logging",
  "Payment Processing",
  "API Response",
  "Data Sync",
  "Firewall Breach",
  "Critical Alert",
  "Server Crash",
  "Service Degradation",
  "Scheduled Maintenance",
  "Malware Detection",
  "Application Deployment",
  "User Registration",
  "Load Balancer Adjustment",
  "Security Patch",
  "Data Migration",
  "Login Attempt",
  "File Upload",
  "Error Notification",
  "Session Timeout",
  "Configuration Change",
  "IP Whitelisting",
];
