version: "3.8"

services:
  critical-events-finder-react-router-dom:
    build: .
    ports:
      - "5001:5001"

    develop:
      watch:
        - path: .
          target: /app
          action: sync
